# SPDX-FileCopyrightText: © Vegard IT GmbH (https://vegardit.com) and contributors
# SPDX-FileContributor: Sebastian Thomschke (https://sebthom.de), Vegard IT GmbH (https://vegardit.com)
# SPDX-License-Identifier: EPL-2.0
# SPDX-ArtifactOfProjectHomePage: https://github.com/vegardit/no-npe
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: Build

on:
  schedule:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
    - cron: "0 15 1 * *"
  push:
    branches-ignore:  # build all branches except:
    - "dependabot/**"  # prevent GHA triggered twice (once for commit to the branch and once for opening/syncing the PR)
    tags-ignore:  # don't build tags
    - "**"
    paths-ignore:
    - ".act*"
    - "**/*.adoc"
    - "**/*.md"
    - ".editorconfig"
    - ".git*"
    - ".github/*.yml"
    - ".github/ISSUE_TEMPLATE/*"
    - ".github/workflows/stale.yml"
    - ".github/workflows/update-eea-files.yml"
  pull_request:
    paths-ignore:
    - ".act*"
    - "**/*.adoc"
    - "**/*.md"
    - ".editorconfig"
    - ".git*"
    - ".github/*.yml"
    - ".github/ISSUE_TEMPLATE/*"
    - ".github/workflows/stale.yml"
    - ".github/workflows/update-eea-files.yml"
  workflow_dispatch:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch
    inputs:
      extra-maven-args:
        description: "Additional command-line arguments to append to all Maven invocations"
        required: false
        default: ""
      debug-with-ssh:
        description: "Start an SSH session for debugging purposes at the end of the build:"
        default: never
        type: choice
        options: [ always, on_failure, on_failure_or_cancelled, never ]
      debug-with-ssh-only-for-actor:
        description: "Limit access to the SSH session to the GitHub user that triggered the job."
        default: true
        type: boolean

jobs:
  ###########################################################
  maven-build:
  ###########################################################
    uses: sebthom/gha-shared/.github/workflows/reusable.maven-build.yml@v1
    with:
      timeout-minutes: 10

      compile-jdk: 11
      extra-jdks: 17,21

      extra-maven-args: ${{ inputs.extra-maven-args }}
      snapshots-branch: mvn-snapshots-repo

      debug-with-ssh: ${{ inputs.debug-with-ssh }}
      debug-with-ssh-only-for-actor: ${{ inputs.debug-with-ssh-only-for-actor }}

    secrets:
      SONATYPE_CENTRAL_USER:  ${{ vars.SONATYPE_CENTRAL_USER }}
      SONATYPE_CENTRAL_TOKEN: ${{ secrets.SONATYPE_CENTRAL_TOKEN }}
      GPG_SIGN_KEY:           ${{ secrets.GPG_SIGN_KEY }}
      GPG_SIGN_KEY_PWD:       ${{ secrets.GPG_SIGN_KEY_PWD }}

    permissions:
      actions: write        # to delete action cache entries
      contents: write       # to create releases (commit to dev branch, create tags)
      pull-requests: write  # for dependabot auto merges
